"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Optional
from mazyr.domain.constitution import Constitution
from mazyr.domain.filter import IntegrityFilter
from mazyr.domain.identity import Identity, Mission
from mazyr.domain.instance_config import InstanceConfig

@dataclass
class BootContext:
    """Context object passed through boot sequence."""
    identity: Optional[Identity] = ...
    mission: Optional[Mission] = ...
    constitution: Optional[Constitution] = ...
    filter: Optional[IntegrityFilter] = ...
    config: Optional[InstanceConfig] = ...
    memory_ready: bool = ...
    llm_ready: bool = ...
    status: str = ...
    errors: list[str] = ...


class Bootstrap:
    """Boot sequence for Mazyr instance. Each step is atomic and can be retried."""
    def __init__(self, config_loader, memory_adapter, llm_router) -> None:
        ...
    
    def boot(self, base_dir: str | Path | None = ...) -> BootContext:
        """Execute full boot sequence."""
        ...
    


