"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional
from mazyr.domain.message import Message
from mazyr.domain.filter import FilterResult

@dataclass
class ChatResult:
    """Result of a chat interaction."""
    success: bool
    reply: Optional[str] = ...
    filter_result: Optional[FilterResult] = ...
    error: Optional[str] = ...
    tokens_used: int = ...


class ChatUseCase:
    """Core chat orchestrator."""
    def __init__(self, identity, mission, filter_engine, memory, llm_router) -> None:
        ...
    
    def receive(self, message: Message) -> ChatResult:
        """Process an incoming message and generate a reply."""
        ...
    


