"""
This type stub file was generated by pyright.
"""

import click
from mazyr.infrastructure.paths import MAZYR_HOME

"""Mazyr CLI -- Modern agentic command-line interface.

Usage:
    mazyr init          Initialize a new Mazyr instance
    mazyr boot          Boot the instance
    mazyr status        Check instance status
    mazyr stop          Stop the instance
    mazyr sync          Sync memory to GitHub
    mazyr chat          Interactive terminal chat
    mazyr --version     Show version
    mazyr --help        Show help

Inspired by: docker, git, gh, ollama
"""
__version__ = ...
console = ...
@click.group(invoke_without_command=True, context_settings=dict(help_option_names=["-h", "--help"]))
@click.option("--version", "-v", is_flag=True, help="Show version and exit.")
@click.pass_context
def cli(ctx, version) -> None:
    """Mazyr — Synthetic Partner Node

    \b
    Quick Start:
        mazyr init      Create your instance
        mazyr boot      Start Mazyr
        mazyr status    Check health
        mazyr chat      Talk to Mazyr

    \b
    Management:
        mazyr stop      Stop Mazyr
        mazyr sync      Sync memory to GitHub
    """
    ...

@cli.command()
@click.option("--base-dir", default=str(MAZYR_HOME), help="Instance directory (default: ~/.mazyr)", show_default=True)
def init(base_dir) -> None:
    """Initialize a new Mazyr instance."""
    ...

@cli.command()
@click.option("--base-dir", default=str(MAZYR_HOME), help="Instance directory (default: ~/.mazyr)")
@click.option("--daemon", is_flag=True, help="Keep running and listen for configured integrations.")
def boot(base_dir, daemon) -> None:
    """Boot the Mazyr instance."""
    ...

@cli.command()
@click.option("--base-dir", default=str(MAZYR_HOME), help="Instance directory (default: ~/.mazyr)")
def status(base_dir) -> None:
    """Check Mazyr instance status."""
    ...

@cli.command()
def stop() -> None:
    """Stop the Mazyr instance."""
    ...

@cli.command()
@click.option("--base-dir", default=str(MAZYR_HOME), help="Instance directory (default: ~/.mazyr)")
def sync(base_dir) -> None:
    """Sync memory snapshot to GitHub."""
    ...

@cli.command()
@click.option("--base-dir", default=str(MAZYR_HOME), help="Instance directory (default: ~/.mazyr)")
def chat(base_dir) -> None:
    """Start interactive terminal chat."""
    ...

if __name__ == "__main__":
    ...
