"""
This type stub file was generated by pyright.
"""

class RelayClient:
    """WebSocket client for cloud relay."""
    def __init__(self, endpoint: str, instance_id: str) -> None:
        ...
    
    async def connect(self) -> None:
        ...
    
    async def send(self, data: dict) -> None:
        ...
    
    async def disconnect(self) -> None:
        ...
    


