"""
This type stub file was generated by pyright.
"""

from fastapi import Request
from mazyr.application.chat import ChatUseCase

app = ...
chat_uc: ChatUseCase = ...
@app.post("/webhook/whatsapp")
async def whatsapp_webhook(request: Request) -> JSONResponse:
    """Receive WhatsApp webhook."""
    ...

@app.post("/webhook/telegram")
async def telegram_webhook(request: Request) -> JSONResponse:
    """Receive Telegram webhook."""
    ...

@app.get("/health")
async def health_check() -> dict[str, str]:
    """Health check endpoint."""
    ...

