"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional

class FilterAction(str, Enum):
    """Actions the integrity filter can take."""
    ALLOW = ...
    DROP = ...
    MODIFY = ...


@dataclass(frozen=True)
class FilterResult:
    """Result of filter processing."""
    action: FilterAction
    original_message: Optional[str] = ...
    modified_message: Optional[str] = ...
    reason: Optional[str] = ...
    matched_rule: Optional[str] = ...


@dataclass(frozen=True)
class FilterRule:
    """Individual rule for the integrity filter."""
    name: str
    action: FilterAction
    pattern_type: str
    patterns: tuple[str, ...]
    description: str
    direction: str = ...


class IntegrityFilter:
    """Programmatic integrity filter."""
    DEFAULT_RULES: tuple[FilterRule, ...] = ...
    def __init__(self, custom_rules: Optional[list[FilterRule]] = ...) -> None:
        ...
    
    def process(self, message: str, context: dict) -> FilterResult:
        """Evaluate message against all applicable rules. Priority: DROP > MODIFY > ALLOW"""
        ...
    


