"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional

@dataclass(frozen=True)
class Identity:
    """Core Identity of a Mazyr instance. Frozen = immutable after creation."""
    instance_name: str
    species: str = ...
    creator_name: str = ...
    creator_contact: Optional[str] = ...
    date_provisioned: str = ...
    vessel_type: str = ...
    def __post_init__(self) -> None:
        ...
    
    @property
    def is_configured(self) -> bool:
        """Returns True if identity has been customized beyond defaults."""
        ...
    


@dataclass
class Mission:
    """Mission configuration determines execution branching."""
    primary: str
    secondary: Optional[str] = ...
    scope: list[str] = ...
    def __post_init__(self) -> None:
        ...
    


