"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass(frozen=True)
class Message:
    """A single message in a conversation."""
    id: str
    content: str
    sender: str
    platform: str
    timestamp: str
    metadata: dict = ...
    @property
    def is_from_creator(self) -> bool:
        ...
    
    @property
    def is_from_instance(self) -> bool:
        ...
    


@dataclass
class Conversation:
    """A collection of messages."""
    id: str
    messages: list[Message] = ...
    created_at: str = ...
    updated_at: str = ...
    def add_message(self, message: Message) -> None:
        ...
    
    def last_n(self, n: int) -> list[Message]:
        ...
    


