"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional
from mazyr.domain.filter import FilterRule
from mazyr.domain.identity import Identity, Mission
from mazyr.domain.instance_config import InstanceConfig

class ConfigLoader:
    """Loads configuration from .mazyr/ directory. Validates using Domain Layer entities."""
    def __init__(self, base_dir: str | Path | None = ...) -> None:
        ...
    
    def load_identity(self, base_dir: str | Path | None = ...) -> Optional[Identity]:
        """Load identity from .mazyr/identity.md"""
        ...
    
    def load_mission(self, base_dir: str | Path | None = ...) -> Optional[Mission]:
        """Load mission from .mazyr/mission.md"""
        ...
    
    def load_config(self) -> Optional[InstanceConfig]:
        """Load runtime config from .mazyr/config.yaml"""
        ...
    
    def load_custom_rules(self) -> list[FilterRule]:
        """Load custom filter rules from .mazyr/filter-custom.json"""
        ...
    


