"""
This type stub file was generated by pyright.
"""

from typing import Optional

class DockerComposeManager:
    """Manages Qdrant container via Docker Compose."""
    def __init__(self, compose_file: Optional[str] = ...) -> None:
        ...
    
    @property
    def is_available(self) -> bool:
        """Check if docker compose is available on this system."""
        ...
    
    def start(self) -> bool:
        """Start Qdrant container. Returns True if successful."""
        ...
    
    def stop(self) -> bool:
        """Stop Qdrant container."""
        ...
    
    def is_running(self) -> bool:
        """Check if Qdrant container is running."""
        ...
    
    def wait_for_healthy(self, timeout: float = ...) -> bool:
        """Wait for Qdrant to be healthy."""
        ...
    


