"""
This type stub file was generated by pyright.
"""

import httpx

class OpenAIEmbeddingAdapter:
    """OpenAI-compatible embeddings client."""
    def __init__(self, api_key: str, base_url: str = ..., model: str = ..., dimensions: int = ..., client: httpx.Client | None = ...) -> None:
        ...
    
    def embed(self, text: str) -> list[float]:
        """Create one embedding vector for text."""
        ...
    


