"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

class FilesystemAdapter:
    """File operations for .mazyr/ directory and memory storage."""
    def __init__(self, base_dir: str | Path | None = ...) -> None:
        ...
    
    def init_mazyr_dir(self) -> None:
        ...
    
    def write_identity(self, content: str) -> None:
        ...
    
    def write_mission(self, content: str) -> None:
        ...
    
    def write_config(self, content: str) -> None:
        ...
    
    def read_file(self, path: str) -> Optional[str]:
        ...
    
    def backup_memory(self, dest: str) -> None:
        ...
    


