"""
This type stub file was generated by pyright.
"""

from enum import Enum

class InferencePreference(str, Enum):
    """Preference for LLM inference routing."""
    LOCAL = ...
    CLOUD = ...
    HYBRID = ...


class LLMRouter:
    """Routes inference requests between local and cloud LLM."""
    def __init__(self, local_llm, cloud_llm, preference: InferencePreference = ...) -> None:
        ...
    
    def initialize(self) -> None:
        ...
    
    def generate(self, prompt: str, complexity: str = ...) -> str:
        ...
    


