"""
This type stub file was generated by pyright.
"""

class CloudLLM:
    """Wrapper for Kimi API (OpenAI-compatible)."""
    def __init__(self, api_key: str, base_url: str = ..., model: str = ...) -> None:
        ...
    
    def generate(self, prompt: str, model: str | None = ..., temperature: float = ..., max_tokens: int = ...) -> str:
        """Generate text using cloud API."""
        ...
    
    def is_available(self) -> bool:
        ...
    


