"""
This type stub file was generated by pyright.
"""

class LocalLLM:
    """Wrapper for llama.cpp local inference."""
    def __init__(self, model_path: str, ngl: int = ..., temp: float = ...) -> None:
        ...
    
    def generate(self, prompt: str, max_tokens: int = ...) -> str:
        """Generate text using local model."""
        ...
    
    def is_available(self) -> bool:
        ...
    


