"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from mazyr.domain.memory_entry import MemoryEntry

class SQLiteMemoryAdapter:
    """Adapter for SQLite database."""
    def __init__(self, db_path: str | Path | None = ...) -> None:
        ...
    
    def connect(self) -> None:
        ...
    
    def add(self, entry: MemoryEntry) -> None:
        ...
    
    def get_recent(self, limit: int = ...) -> list[MemoryEntry]:
        ...
    
    def count(self) -> int:
        ...
    
    def type_distribution(self) -> dict:
        ...
    
    def close(self) -> None:
        ...
    


