"""
This type stub file was generated by pyright.
"""

from typing import Optional
from mazyr.domain.memory_entry import MemoryEntry, MemoryQuery

class QdrantMemoryAdapter:
    """Adapter for Qdrant vector database."""
    COLLECTION_NAME = ...
    def __init__(self, host: str = ..., port: int = ..., vector_size: int = ..., embedder=..., client=..., collection_name: str | None = ...) -> None:
        ...
    
    def connect(self) -> None:
        ...
    
    def add(self, entry: MemoryEntry, embedding: Optional[list[float]] = ...) -> None:
        ...
    
    def search(self, query: MemoryQuery, query_embedding: Optional[list[float]] = ...) -> list[MemoryEntry]:
        ...
    


