"""
This type stub file was generated by pyright.
"""

from mazyr.domain.memory_entry import MemoryEntry, MemoryQuery

class MemoryRouter:
    """Routes durable memory to SQLite and semantic retrieval to Qdrant."""
    def __init__(self, durable_memory, semantic_memory=...) -> None:
        ...
    
    def connect(self) -> None:
        ...
    
    def add(self, entry: MemoryEntry) -> None:
        ...
    
    def search(self, query: MemoryQuery) -> list[MemoryEntry]:
        ...
    
    def close(self) -> None:
        ...
    


