"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Callable

class WhatsAppAdapter:
    """WhatsApp Web adapter using Playwright."""
    def __init__(self, session_dir: str | Path | None = ...) -> None:
        ...
    
    async def start(self) -> None:
        ...
    
    async def send(self, chat_id: str, message: str) -> None:
        ...
    
    async def listen(self, handler: Callable):
        ...
    
    async def stop(self) -> None:
        ...
    


