"""
This type stub file was generated by pyright.
"""

from typing import Callable

class TelegramAdapter:
    """Telegram Bot adapter using HTTP API."""
    def __init__(self, bot_token: str) -> None:
        ...
    
    def send_message(self, chat_id: int, text: str) -> None:
        ...
    
    def get_updates(self, limit: int = ...) -> list[dict]:
        ...
    
    def listen(self, handler: Callable):
        ...
    


